/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated.timetable'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated.payroll'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated.messages'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated.hr'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated.finance'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated.classes'
import { Route as AuthenticatedBoardingRouteImport } from './routes/_authenticated.boarding'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated.attendance'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated.admissions'
import { Route as AuthenticatedAcceptInviteRouteImport } from './routes/_authenticated.accept-invite'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated.students_.new'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated.students.$studentId'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated.settings.audit'
import { Route as AuthenticatedReportsCoefficientsRouteImport } from './routes/_authenticated.reports.coefficients'
import { Route as AuthenticatedPayrollRunIdRouteImport } from './routes/_authenticated.payroll.$runId'
import { Route as AuthenticatedHrStaffIdRouteImport } from './routes/_authenticated.hr.$staffId'
import { Route as AuthenticatedAdmissionsNewRouteImport } from './routes/_authenticated.admissions.new'
import { Route as AuthenticatedFinanceReceiptPaymentIdRouteImport } from './routes/_authenticated.finance.receipt.$paymentId'
import { Route as AuthenticatedReportsBulletinStudentIdSequenceRouteImport } from './routes/_authenticated.reports.bulletin.$studentId.$sequence'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardingRoute = AuthenticatedBoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcceptInviteRoute =
  AuthenticatedAcceptInviteRouteImport.update({
    id: '/accept-invite',
    path: '/accept-invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students_/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/settings/audit',
    path: '/settings/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCoefficientsRoute =
  AuthenticatedReportsCoefficientsRouteImport.update({
    id: '/coefficients',
    path: '/coefficients',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPayrollRunIdRoute =
  AuthenticatedPayrollRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthenticatedPayrollRoute,
  } as any)
const AuthenticatedHrStaffIdRoute = AuthenticatedHrStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedAdmissionsNewRoute =
  AuthenticatedAdmissionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdmissionsRoute,
  } as any)
const AuthenticatedFinanceReceiptPaymentIdRoute =
  AuthenticatedFinanceReceiptPaymentIdRouteImport.update({
    id: '/receipt/$paymentId',
    path: '/receipt/$paymentId',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedReportsBulletinStudentIdSequenceRoute =
  AuthenticatedReportsBulletinStudentIdSequenceRouteImport.update({
    id: '/bulletin/$studentId/$sequence',
    path: '/bulletin/$studentId/$sequence',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/accept-invite': typeof AuthenticatedAcceptInviteRoute
  '/admissions': typeof AuthenticatedAdmissionsRouteWithChildren
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/boarding': typeof AuthenticatedBoardingRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/payroll': typeof AuthenticatedPayrollRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/timetable': typeof AuthenticatedTimetableRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admissions/new': typeof AuthenticatedAdmissionsNewRoute
  '/hr/$staffId': typeof AuthenticatedHrStaffIdRoute
  '/payroll/$runId': typeof AuthenticatedPayrollRunIdRoute
  '/reports/coefficients': typeof AuthenticatedReportsCoefficientsRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/finance/receipt/$paymentId': typeof AuthenticatedFinanceReceiptPaymentIdRoute
  '/reports/bulletin/$studentId/$sequence': typeof AuthenticatedReportsBulletinStudentIdSequenceRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/accept-invite': typeof AuthenticatedAcceptInviteRoute
  '/admissions': typeof AuthenticatedAdmissionsRouteWithChildren
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/boarding': typeof AuthenticatedBoardingRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/payroll': typeof AuthenticatedPayrollRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/timetable': typeof AuthenticatedTimetableRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/admissions/new': typeof AuthenticatedAdmissionsNewRoute
  '/hr/$staffId': typeof AuthenticatedHrStaffIdRoute
  '/payroll/$runId': typeof AuthenticatedPayrollRunIdRoute
  '/reports/coefficients': typeof AuthenticatedReportsCoefficientsRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/finance/receipt/$paymentId': typeof AuthenticatedFinanceReceiptPaymentIdRoute
  '/reports/bulletin/$studentId/$sequence': typeof AuthenticatedReportsBulletinStudentIdSequenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/accept-invite': typeof AuthenticatedAcceptInviteRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/boarding': typeof AuthenticatedBoardingRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admissions/new': typeof AuthenticatedAdmissionsNewRoute
  '/_authenticated/hr/$staffId': typeof AuthenticatedHrStaffIdRoute
  '/_authenticated/payroll/$runId': typeof AuthenticatedPayrollRunIdRoute
  '/_authenticated/reports/coefficients': typeof AuthenticatedReportsCoefficientsRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students_/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/finance/receipt/$paymentId': typeof AuthenticatedFinanceReceiptPaymentIdRoute
  '/_authenticated/reports/bulletin/$studentId/$sequence': typeof AuthenticatedReportsBulletinStudentIdSequenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/accept-invite'
    | '/admissions'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/finance'
    | '/hr'
    | '/messages'
    | '/payroll'
    | '/reports'
    | '/students'
    | '/timetable'
    | '/wallet'
    | '/admissions/new'
    | '/hr/$staffId'
    | '/payroll/$runId'
    | '/reports/coefficients'
    | '/settings/audit'
    | '/settings/users'
    | '/students/$studentId'
    | '/students/new'
    | '/settings/'
    | '/finance/receipt/$paymentId'
    | '/reports/bulletin/$studentId/$sequence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/accept-invite'
    | '/admissions'
    | '/attendance'
    | '/boarding'
    | '/classes'
    | '/finance'
    | '/hr'
    | '/messages'
    | '/payroll'
    | '/reports'
    | '/students'
    | '/timetable'
    | '/wallet'
    | '/'
    | '/admissions/new'
    | '/hr/$staffId'
    | '/payroll/$runId'
    | '/reports/coefficients'
    | '/settings/audit'
    | '/settings/users'
    | '/students/$studentId'
    | '/students/new'
    | '/settings'
    | '/finance/receipt/$paymentId'
    | '/reports/bulletin/$studentId/$sequence'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/accept-invite'
    | '/_authenticated/admissions'
    | '/_authenticated/attendance'
    | '/_authenticated/boarding'
    | '/_authenticated/classes'
    | '/_authenticated/finance'
    | '/_authenticated/hr'
    | '/_authenticated/messages'
    | '/_authenticated/payroll'
    | '/_authenticated/reports'
    | '/_authenticated/students'
    | '/_authenticated/timetable'
    | '/_authenticated/wallet'
    | '/_authenticated/'
    | '/_authenticated/admissions/new'
    | '/_authenticated/hr/$staffId'
    | '/_authenticated/payroll/$runId'
    | '/_authenticated/reports/coefficients'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/users'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students_/new'
    | '/_authenticated/settings/'
    | '/_authenticated/finance/receipt/$paymentId'
    | '/_authenticated/reports/bulletin/$studentId/$sequence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boarding': {
      id: '/_authenticated/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof AuthenticatedBoardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accept-invite': {
      id: '/_authenticated/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthenticatedAcceptInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students_/new': {
      id: '/_authenticated/students_/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/coefficients': {
      id: '/_authenticated/reports/coefficients'
      path: '/coefficients'
      fullPath: '/reports/coefficients'
      preLoaderRoute: typeof AuthenticatedReportsCoefficientsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/payroll/$runId': {
      id: '/_authenticated/payroll/$runId'
      path: '/$runId'
      fullPath: '/payroll/$runId'
      preLoaderRoute: typeof AuthenticatedPayrollRunIdRouteImport
      parentRoute: typeof AuthenticatedPayrollRoute
    }
    '/_authenticated/hr/$staffId': {
      id: '/_authenticated/hr/$staffId'
      path: '/$staffId'
      fullPath: '/hr/$staffId'
      preLoaderRoute: typeof AuthenticatedHrStaffIdRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/admissions/new': {
      id: '/_authenticated/admissions/new'
      path: '/new'
      fullPath: '/admissions/new'
      preLoaderRoute: typeof AuthenticatedAdmissionsNewRouteImport
      parentRoute: typeof AuthenticatedAdmissionsRoute
    }
    '/_authenticated/finance/receipt/$paymentId': {
      id: '/_authenticated/finance/receipt/$paymentId'
      path: '/receipt/$paymentId'
      fullPath: '/finance/receipt/$paymentId'
      preLoaderRoute: typeof AuthenticatedFinanceReceiptPaymentIdRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/reports/bulletin/$studentId/$sequence': {
      id: '/_authenticated/reports/bulletin/$studentId/$sequence'
      path: '/bulletin/$studentId/$sequence'
      fullPath: '/reports/bulletin/$studentId/$sequence'
      preLoaderRoute: typeof AuthenticatedReportsBulletinStudentIdSequenceRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
  }
}

interface AuthenticatedAdmissionsRouteChildren {
  AuthenticatedAdmissionsNewRoute: typeof AuthenticatedAdmissionsNewRoute
}

const AuthenticatedAdmissionsRouteChildren: AuthenticatedAdmissionsRouteChildren =
  {
    AuthenticatedAdmissionsNewRoute: AuthenticatedAdmissionsNewRoute,
  }

const AuthenticatedAdmissionsRouteWithChildren =
  AuthenticatedAdmissionsRoute._addFileChildren(
    AuthenticatedAdmissionsRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceReceiptPaymentIdRoute: typeof AuthenticatedFinanceReceiptPaymentIdRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceReceiptPaymentIdRoute:
    AuthenticatedFinanceReceiptPaymentIdRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrStaffIdRoute: typeof AuthenticatedHrStaffIdRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrStaffIdRoute: AuthenticatedHrStaffIdRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedPayrollRouteChildren {
  AuthenticatedPayrollRunIdRoute: typeof AuthenticatedPayrollRunIdRoute
}

const AuthenticatedPayrollRouteChildren: AuthenticatedPayrollRouteChildren = {
  AuthenticatedPayrollRunIdRoute: AuthenticatedPayrollRunIdRoute,
}

const AuthenticatedPayrollRouteWithChildren =
  AuthenticatedPayrollRoute._addFileChildren(AuthenticatedPayrollRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsCoefficientsRoute: typeof AuthenticatedReportsCoefficientsRoute
  AuthenticatedReportsBulletinStudentIdSequenceRoute: typeof AuthenticatedReportsBulletinStudentIdSequenceRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsCoefficientsRoute: AuthenticatedReportsCoefficientsRoute,
  AuthenticatedReportsBulletinStudentIdSequenceRoute:
    AuthenticatedReportsBulletinStudentIdSequenceRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcceptInviteRoute: typeof AuthenticatedAcceptInviteRoute
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRouteWithChildren
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBoardingRoute: typeof AuthenticatedBoardingRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcceptInviteRoute: AuthenticatedAcceptInviteRoute,
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRouteWithChildren,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBoardingRoute: AuthenticatedBoardingRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
