// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrnatylmbjpiyekkmdlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybmF0eWxtYmpwaXlla2ttZGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM3OTQ0NzQsImV4cCI6MjA5OTM3MDQ3NH0.fIzQ3b-27t5GL722QYNCMeoi716CRptL9HoeBXqgjYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});